#!/bin/sh

echo "[LTSDWAN] Initial network & system setup..."

uci -q delete network.lan
uci -q delete network.wan

# WAN eth0
uci set network.wan=interface
uci set network.wan.device='eth0'
uci set network.wan.proto='dhcp'

# LAN eth1-eth4 (172 段)
uci set network.lan1=interface
uci set network.lan1.device='eth1'
uci set network.lan1.proto='static'
uci set network.lan1.ipaddr='172.16.10.1'
uci set network.lan1.netmask='255.255.255.0'

uci set network.lan2=interface
uci set network.lan2.device='eth2'
uci set network.lan2.proto='static'
uci set network.lan2.ipaddr='172.16.20.1'
uci set network.lan2.netmask='255.255.255.0'

uci set network.lan3=interface
uci set network.lan3.device='eth3'
uci set network.lan3.proto='static'
uci set network.lan3.ipaddr='172.16.30.1'
uci set network.lan3.netmask='255.255.255.0'

uci set network.lan4=interface
uci set network.lan4.device='eth4'
uci set network.lan4.proto='static'
uci set network.lan4.ipaddr='172.16.40.1'
uci set network.lan4.netmask='255.255.255.0'

# 管理口 eth5
uci set network.mgmt=interface
uci set network.mgmt.device='eth5'
uci set network.mgmt.proto='static'
uci set network.mgmt.ipaddr='192.168.188.254'
uci set network.mgmt.netmask='255.255.255.0'

uci commit network

# 防火墙
uci -q delete firewall.@zone[0]
uci -q delete firewall.@zone[1]

uci add firewall zone
uci set firewall.@zone[-1].name='lan'
uci set firewall.@zone[-1].input='ACCEPT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='ACCEPT'
uci add_list firewall.@zone[-1].network='lan1'
uci add_list firewall.@zone[-1].network='lan2'
uci add_list firewall.@zone[-1].network='lan3'
uci add_list firewall.@zone[-1].network='lan4'
uci add_list firewall.@zone[-1].network='mgmt'

uci add firewall zone
uci set firewall.@zone[-1].name='wan'
uci set firewall.@zone[-1].input='REJECT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='REJECT'
uci set firewall.@zone[-1].masq='1'
uci add_list firewall.@zone[-1].network='wan'

uci add firewall forwarding
uci set firewall.@forwarding[-1].src='lan'
uci set firewall.@forwarding[-1].dest='wan'

uci commit firewall

# Web 端口
uci delete uhttpd.main.listen_http
uci add_list uhttpd.main.listen_http='0.0.0.0:10834'
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd

# root 密码
echo "root:@Feng%Zi!&" | chpasswd

/etc/init.d/network restart
/etc/init.d/firewall restart
/etc/init.d/uhttpd restart

exit 0
