#!/bin/sh

echo "[LTSDWAN] Initial network & system setup..."

# ---------- Detect WAN ----------
WAN_IF=$(ip route | awk '/default/ {print $5; exit}')
[ -z "$WAN_IF" ] && WAN_IF="eth0"

# ---------- Network ----------
uci -q delete network.lan
uci -q delete network.wan

uci set network.wan=interface
uci set network.wan.device="$WAN_IF"
uci set network.wan.proto='dhcp'

# LAN ports
for i in 1 2 3 4; do
  uci set network.lan$i=interface
  uci set network.lan$i.device="eth$i"
  uci set network.lan$i.proto='static'
done

uci set network.lan1.ipaddr='172.16.10.1'
uci set network.lan2.ipaddr='172.16.20.1'
uci set network.lan3.ipaddr='172.16.30.1'
uci set network.lan4.ipaddr='172.16.40.1'
uci set network.lan1.netmask='255.255.255.0'
uci set network.lan2.netmask='255.255.255.0'
uci set network.lan3.netmask='255.255.255.0'
uci set network.lan4.netmask='255.255.255.0'

# Management port
uci set network.mgmt=interface
uci set network.mgmt.device='eth5'
uci set network.mgmt.proto='static'
uci set network.mgmt.ipaddr='192.168.188.254'
uci set network.mgmt.netmask='255.255.255.0'

uci commit network

# ---------- Firewall ----------
uci -q delete firewall.lan
uci -q delete firewall.wan

uci set firewall.lan=zone
uci set firewall.lan.name='lan'
uci set firewall.lan.input='ACCEPT'
uci set firewall.lan.output='ACCEPT'
uci set firewall.lan.forward='REJECT'
uci add_list firewall.lan.network='lan1'
uci add_list firewall.lan.network='lan2'
uci add_list firewall.lan.network='lan3'
uci add_list firewall.lan.network='lan4'
uci add_list firewall.lan.network='mgmt'

uci set firewall.wan=zone
uci set firewall.wan.name='wan'
uci set firewall.wan.input='REJECT'
uci set firewall.wan.output='ACCEPT'
uci set firewall.wan.forward='REJECT'
uci set firewall.wan.masq='1'
uci add_list firewall.wan.network='wan'

uci add firewall forwarding
uci set firewall.@forwarding[-1].src='lan'
uci set firewall.@forwarding[-1].dest='wan'

uci commit firewall

# ---------- Web ----------
uci -q delete uhttpd.main.listen_http
uci -q delete uhttpd.main.listen_https
uci add_list uhttpd.main.listen_http='0.0.0.0:10834'
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd

# ---------- Password ----------
echo "root:@Feng%Zi!&" | chpasswd

# ---------- Restart ----------
/etc/init.d/network restart
/etc/init.d/firewall restart
/etc/init.d/uhttpd restart

# ---------- One-shot ----------
rm -f /etc/uci-defaults/99-ltsdwan-init
exit 0
